# _config.yml
# fp.michalspano.com
# Author: Michal Spano
# Theme: https://github.com/niklasbuschmann/contrast

remote_theme: niklasbuschmann/contrast@v2.11

title: "FuncProg Î»"
author: "Michal Spano"
description: "Haskell done unironically."
permalink: /:title/
excerpt_separator: "\n\n" # How many lines (of the preview) to display?
date_format: "%Y/%m/%d"
lang: "en"

show_excerpts: true
show_frame: true
show_sidebar: true
minimal: false # a minimal preset layout?

navigation: # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"} # home with list of posts
  - {file: "about.md"}   # explain the repo

external:
  - {title: Mail, icon: envelope, url: "mailto:spano@michalspano.com"}
  - {title: Github, icon: github, url: "https://github.com/michalspano"}
# - {title: Subscribe, icon: rss, url: "/feed.xml"} # TODO

# Plugins
plugins:
  - jekyll-remote-theme

exclude: ["src", "_site", "readme.md"] # don't include raw Haskell src, etc.
